[package]
name = "uiplay"
version = "0.6.0"
description = "UiPlay"
authors = ["saboooor"]
license = ""
repository = "https://github.com/LuminescentDev/uiplay.git"
edition = "2024"
rust-version = "1.96.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
log = "0.4.34"
tauri = { version = "2.11.6", features = ["tray-icon"] }
tauri-plugin-log = "2.9.2"
tauri-plugin-fs = "2.5.2"
discord-rich-presence = "1.1.0"
regex = "1.13.1"
base64 = "0.23.1"
libc = "0.2.189"
reqwest = { version = "0.13.5", features = ["query"] }
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }
