#!/usr/bin/env bash
set -e

app_dir="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="${app_dir}/usr/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export QT_PLUGIN_PATH="${app_dir}/usr/plugins${QT_PLUGIN_PATH:+:${QT_PLUGIN_PATH}}"
export QML2_IMPORT_PATH="${app_dir}/usr/qml${QML2_IMPORT_PATH:+:${QML2_IMPORT_PATH}}"

exec "${app_dir}/usr/bin/uiplay-qt" "$@"
